import { useState } from "react";
import type { ApiPost } from "../hooks";

type FeedProps = { mode?: "feed" | "fishki"; posts: ApiPost[]; loading: boolean; onOpenArticle: (post: ApiPost) => void; onOpenProfile: (userId: number) => void };
type Filter = "all" | "article";
const filters: Array<{ id: Filter; label: string }> = [{ id: "all", label: "Все" }, { id: "article", label: "Статьи" }];

export function Feed({ mode = "feed", posts, loading, onOpenArticle, onOpenProfile }: FeedProps) {
  const [filter, setFilter] = useState<Filter>("all");
  const isFishki = mode === "fishki";
  const visiblePosts = isFishki ? posts.filter((post) => post.type === "tip") : filter === "all" ? posts : posts.filter((post) => post.type === filter);
  return <main className="feed-page"><div className="feed-wrap">{isFishki ? <section className="journal-intro"><p>Туристическое агентство «Под солнцем»</p><h1>Фишки</h1><div className="ornament"><i />◆<i /></div><div className="intro-text">Короткие советы от менеджеров, которые сами были в путешествии.</div></section> : <section className="journal-intro"><p>Туристическое агентство «Под солнцем»</p><h1>Журнал о путешествиях <b>без прикрас</b></h1><div className="ornament"><i />◆<i /></div><div className="intro-text">Короткие фишки, проверенные отзывы и большие разборы направлений — от менеджеров, которые сами там были.</div></section>}{!isFishki && <div className="feed-filters">{filters.map((item) => <button key={item.id} onClick={() => setFilter(item.id)} className={filter === item.id ? "current" : ""}>{item.label}</button>)}</div>}{loading && <div className="comment-skeleton"><i /><i /><i /></div>}{visiblePosts.map((post) => <PostCard key={post.id} post={post} onOpen={() => onOpenArticle(post)} onOpenProfile={() => onOpenProfile(post.author.id)} />)}{!loading && !visiblePosts.length && <div className="empty-comments">Публикаций в этом разделе пока нет.</div>}<section className="tour-cta"><div><h2>Подберём тур под ваш бюджет</h2><p>Ответьте на пять вопросов в боте — менеджер пришлёт три варианта с ценами.</p></div><a href="https://t.me/pod_solncem_travel_bot" target="_blank" rel="noreferrer">Подобрать тур →</a></section></div></main>;
}
function PostCard({ post, onOpen, onOpenProfile }: { post: ApiPost; onOpen: () => void; onOpenProfile: () => void }) { const kind = post.type === "video_review" ? "video" : post.type; if (kind === "tip") return <article className="post-card tip-card"><div className="tip-mark">✦</div><div><p className="post-tag">Фишка</p><h2 onClick={onOpen}>{post.title}</h2><AuthorLink post={post} onOpenProfile={onOpenProfile} /><p>{post.body}</p><PostActions onOpen={onOpen} /></div></article>; if (kind === "video") return <article className="post-card video-card"><div className="video-cover"><button aria-label="Смотреть видео">▶</button><span>Под солнцем</span>{post.shot_at && <b>Снято {new Date(post.shot_at).toLocaleDateString("ru-RU")}</b>}</div><h2 onClick={onOpen}>{post.title}</h2><AuthorLink post={post} onOpenProfile={onOpenProfile} /><p>{post.body}</p><PostActions onOpen={onOpen} /></article>; return <article className="post-card article-card"><div className="article-cover"><span>Под солнцем</span></div><p className="post-tag">Статья · {post.views} просмотров</p><h2 onClick={onOpen}>{post.title}</h2><AuthorLink post={post} onOpenProfile={onOpenProfile} /><p>{post.body}</p><PostActions onOpen={onOpen} /></article>; }
function AuthorLink({ post, onOpenProfile }: { post: ApiPost; onOpenProfile: () => void }) { return <button className="author-profile-link" onClick={onOpenProfile}>Автор: {post.author.name}</button>; }
function PostActions({ onOpen }: { onOpen: () => void }) { return <div className="post-actions"><button onClick={onOpen}>Читать дальше →</button><button onClick={onOpen}>◌ Обсуждение</button></div>; }
