import { useState } from "react";
import { type Review, useReviews } from "../hooks";

export function Reviews({ onError, onPrivacy }: { onError: (message: string) => void; onPrivacy: () => void }) {
  const { value, loading, create } = useReviews(); const [rating, setRating] = useState(5); const [name, setName] = useState(""); const [body, setBody] = useState(""); const [consent, setConsent] = useState(false); const [pending, setPending] = useState<Review[]>([]);
  const submit = async () => { if (!name.trim() || !body.trim() || !consent) return; try { const review = await create({ author_name: name, body, rating }); setPending((items) => [review, ...items]); setName(""); setBody(""); } catch (cause) { onError(cause instanceof Error ? cause.message : "Не удалось отправить отзыв"); } };
  return <main className="section-page reviews-page"><h1>Отзывы</h1><p className="page-description">Пишут те, кто ездил с нами. Каждый отзыв читает менеджер перед публикацией.</p><section className="surface-card review-form"><h2>Оставить отзыв</h2><p>Опубликуем после проверки менеджером — обычно в течение рабочего дня.</p><div className="form-grid"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Как вас зовут" /><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Что понравилось, что нет — по-честному" /></div><div className="form-actions"><div className="rating"><span>Оценка</span>{[1, 2, 3, 4, 5].map((star) => <button key={star} aria-label={`Оценка ${star}`} onClick={() => setRating(star)} className={star <= rating ? "star active" : "star"}>★</button>)}</div><label><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /> Согласен с <button onClick={onPrivacy}>политикой обработки данных</button></label><button className="panel-button" onClick={submit} disabled={!consent}>Отправить</button></div></section>{pending.length > 0 && <section className="pending-section"><div className="section-heading"><h2>На проверке</h2><span>{pending.length}</span></div>{pending.map((review) => <ReviewCard key={review.id} review={review} pending />)}</section>}<section className="review-list">{loading && <div className="comment-skeleton"><i /><i /></div>}{(value ?? []).map((review) => <ReviewCard key={review.id} review={review} />)}</section></main>;
}
function ReviewCard({ review, pending = false }: { review: Review; pending?: boolean }) { return <article className={pending ? "review-card pending-review" : "review-card"}><header><span className="avatar avatar-1" /><div><strong>{review.author_name}</strong><small>{pending ? "ожидает проверки" : "проверено агентством"}</small></div><b>{"★".repeat(review.rating)}</b></header><p>{review.body}</p>{pending && <small className="pending-label">ждёт проверки менеджером</small>}</article>; }
